### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by Qazzquimby** [Rivals-Workshop-Community-Projects/rivals_workshop_guide#5]
Guide the user through minimal setup, and give them some things to try editing.

Have
- [x]  a big bag of quick changes they can make. 
- [x] Change movement attributes, 
- [x] mess with attack files (preferably Wuffie's), 
- [ ] edit an animation, 
- [ ] change a value in a special attack.
- [ ] Everything important in mawrals guide

- How to learn more
- [ ] Intro art workflow
- [ ] Intro programming workflow
- [ ] Debugging and a troubleshooting section
